server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhangjia
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.springboot1.entity
  configuration:
    map-underscore-to-camel-case: true
